export const saveSlide = (payload) => ({ type: 'SAVE_SLIDE', payload })
export const deleteSlide = (payload) => ({ type: 'DELETE_SLIDE', payload })
// export const moveSlide = (payload) => ({ type: 'MOVE_SLIDE', payload })
export const goToSlide = (payload) => ({ type: 'GO_TO_SLIDE', payload })
export const addSlide = () => ({ type: 'ADD_SLIDE' })
export const nextSlide = () => ({ type: 'NEXT_SLIDE' })
export const previousSlide = () => ({ type: 'PREVIOUS_SLIDE' })
